### ISSUE TITLE
リコが GitHub 使えない

### ISSUE THREAD

**Issue by Gitomoking** [oitakosen-s13/report-manegement#1]
- [x] ローカルに report-management と対応するフォルダ（report_management）を作成する
- [x] そのフォルダ内で `git init` を実行し、git によるバージョン管理をできるようにする
- [x] `git remote add origin git@github.com:oitakosen-s13/report-manegement.git` を実行し、ローカルの report_management フォルダと report-management リポジトリーを接続する
- [x] `git pull origin master` を実行し、report-management リポジトリのファイルをクローン（ローカルにコピー）する
- [x] `git branch riko-use-github` を実行し、作業用ブランチを作成する
- [x] `report_management/README.md` を次のように編集する：「田中りこぷりん」を「田中理瑚」に変更する
- [x] `git status` を実行し、`README.md` に変更があることを確認する
- [x] `git add README.md` を実行し、コミット対象のファイルを選択する
- [x] `git commit -m "Fix riko's name"` のように実行し、編集結果をコミット（保存みたいなもの）する
- [x] `git push origin riko-use-github` を実行し、コミットを GitHub 上のリポジトリに反映させる
- [x] GitHub を開き、Pull Request を作成する
- [x] master ブランチに merge し、README の変更が反映されたことを確認する
- [x] merge 後、riko-use-github ブランチを削除する

**Comment by Gitomoking** [comment]
- [ ] Git bush を開く
- [ ] 適当な場所に移動する。例：cd ~/src
- [ ] `mkdir report_management` でフォルダを作成する

**Comment by TanakaRiko** [comment]
![10](https://user-images.githubusercontent.com/39749458/41281201-c6e74f2a-6e6b-11e8-9096-57ac67d9c4a2.PNG)
リポジトリに反映できてない..？

**Comment by Gitomoking** [comment]
@TanakaRiko ごめん、設定ミスしてた。
たぶんもう push できる。

**Comment by TanakaRiko** [comment]
Pull requestが作れなくて泣いてる。

**Comment by Gitomoking** [comment]
ブランチの内容が更新されていないので、push ができていないのかも

**Comment by Gitomoking** [comment]
https://github.com/oitakosen-s13/report-manegement/pull/5

https://github.com/oitakosen-s13/report-manegement/pull/6
