### ISSUE TITLE
React がわからない

### ISSUE THREAD

**Issue by Gitomoking** [oitakosen-s13/report-manegement#4]
- [ ] [Tutorial: Intro To React](https://reactjs.org/tutorial/tutorial.html)

**Comment by sh-tech** [comment]
@Gitomoking 

- [ ] ドットインストール React：https://dotinstall.com/lessons/basic_reactjs

**Comment by sh-tech** [comment]
@Gitomoking 
Qiita デザイン関係のフレームワークまとめ：https://qiita.com/tashxii/items/6e3e25e8b0f690570920
